version: '3'
services:
  web:
    image: nginx
    ports:
      - 86:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf


  php-fpm:
    build: .
    volumes:
      - .:/var/www/html

  db:
    ports:
      - 54323:5432
    image: postgres:14.1
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpwd